export const SITE_NAME = "Xelnova";
export const SITE_DESCRIPTION = "Your one-stop marketplace for electronics, fashion, home & more.";
export const SUPPORT_PHONE = "1800-123-4567";

export const NAV_CATEGORIES = [
  {
    id: 1,
    name: "Electronics",
    slug: "electronics",
    children: [
      {
        id: 11,
        name: "Mobiles",
        slug: "mobiles",
        children: [
          { id: 111, name: "Smartphones", slug: "smartphones" },
          { id: 112, name: "Feature Phones", slug: "feature-phones" },
          { id: 113, name: "Mobile Accessories", slug: "mobile-accessories" },
        ],
      },
      {
        id: 12,
        name: "Laptops",
        slug: "laptops",
        children: [
          { id: 121, name: "Gaming Laptops", slug: "gaming-laptops" },
          { id: 122, name: "Ultrabooks", slug: "ultrabooks" },
          { id: 123, name: "Budget Laptops", slug: "budget-laptops" },
        ],
      },
      {
        id: 13,
        name: "Audio",
        slug: "audio",
        children: [
          { id: 131, name: "Headphones", slug: "headphones" },
          { id: 132, name: "Speakers", slug: "speakers" },
          { id: 133, name: "Earbuds", slug: "earbuds" },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Fashion",
    slug: "fashion",
    children: [
      {
        id: 21,
        name: "Men",
        slug: "men",
        children: [
          { id: 211, name: "T-Shirts", slug: "t-shirts" },
          { id: 212, name: "Shirts", slug: "shirts" },
          { id: 213, name: "Jeans", slug: "jeans" },
        ],
      },
      {
        id: 22,
        name: "Women",
        slug: "women",
        children: [
          { id: 221, name: "Tops", slug: "tops" },
          { id: 222, name: "Dresses", slug: "dresses" },
          { id: 223, name: "Ethnic Wear", slug: "ethnic-wear" },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Home & Furniture",
    slug: "home-furniture",
    children: [
      {
        id: 31,
        name: "Furniture",
        slug: "furniture",
        children: [
          { id: 311, name: "Sofas", slug: "sofas" },
          { id: 312, name: "Beds", slug: "beds" },
          { id: 313, name: "Tables", slug: "tables" },
        ],
      },
      {
        id: 32,
        name: "Kitchen",
        slug: "kitchen",
        children: [
          { id: 321, name: "Cookware", slug: "cookware" },
          { id: 322, name: "Appliances", slug: "appliances" },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Beauty & Health",
    slug: "beauty-health",
    children: [
      {
        id: 41,
        name: "Skincare",
        slug: "skincare",
        children: [
          { id: 411, name: "Moisturizers", slug: "moisturizers" },
          { id: 412, name: "Sunscreens", slug: "sunscreens" },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Sports & Fitness",
    slug: "sports-fitness",
    children: [],
  },
  {
    id: 6,
    name: "Books & Stationery",
    slug: "books-stationery",
    children: [],
  },
  {
    id: 7,
    name: "Grocery",
    slug: "grocery",
    children: [],
  },
];

export const FOOTER_LINKS = {
  about: [
    { name: "Contact Us", href: "/contact" },
    { name: "About Us", href: "/about" },
    { name: "Careers", href: "/page/careers" },
    { name: "Press", href: "/page/press" },
    { name: "Corporate Information", href: "/page/corporate-information" },
  ],
  help: [
    { name: "Payments", href: "/page/payments" },
    { name: "Shipping", href: "/page/shipping" },
    { name: "Cancellation & Returns", href: "/page/cancellation-returns" },
    { name: "FAQ", href: "/faq" },
    { name: "Report Infringement", href: "/page/report-infringement" },
  ],
  tools: [
    { name: "IFSC Code Lookup", href: "/ifsc" },
    { name: "GSTIN Lookup", href: "/gstin" },
  ],
  policy: [
    { name: "Return Policy", href: "/returns" },
    { name: "Terms of Use", href: "/terms" },
    { name: "Security", href: "/page/security" },
    { name: "Privacy", href: "/privacy" },
    { name: "Sitemap", href: "/page/sitemap" },
  ],
};

export const MOCK_CATEGORIES = [
  {
    id: 1,
    name: "Mobiles",
    slug: "mobiles",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=200&h=200&fit=crop",
  },
  {
    id: 2,
    name: "Fashion",
    slug: "fashion",
    image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=200&h=200&fit=crop",
  },
  {
    id: 3,
    name: "Electronics",
    slug: "electronics",
    image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=200&h=200&fit=crop",
  },
  {
    id: 4,
    name: "Home",
    slug: "home-furniture",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=200&h=200&fit=crop",
  },
  {
    id: 5,
    name: "Beauty",
    slug: "beauty-health",
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=200&h=200&fit=crop",
  },
  {
    id: 6,
    name: "Sports",
    slug: "sports-fitness",
    image: "https://placehold.co/200x200/e8ecf1/8d95a5?text=Sports",
  },
  {
    id: 7,
    name: "Books",
    slug: "books-stationery",
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=200&h=200&fit=crop",
  },
  {
    id: 8,
    name: "Grocery",
    slug: "grocery",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&h=200&fit=crop",
  },
];

export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: "Samsung Galaxy S25 Ultra 5G (Titanium Black, 256GB)",
    slug: "samsung-galaxy-s25-ultra",
    image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&h=500&fit=crop",
    price: 79999,
    originalPrice: 94999,
    rating: 4.6,
    reviewsCount: 3842,
    brand: "Samsung",
    freeDelivery: true,
  },
  {
    id: 2,
    name: "Apple MacBook Air M3 Chip 15-inch (Midnight, 16GB)",
    slug: "macbook-air-m3",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=500&fit=crop",
    price: 114990,
    originalPrice: 134990,
    rating: 4.8,
    reviewsCount: 2156,
    brand: "Apple",
    freeDelivery: true,
  },
  {
    id: 3,
    name: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
    slug: "sony-wh-1000xm5",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=500&fit=crop",
    price: 24990,
    originalPrice: 29990,
    rating: 4.7,
    reviewsCount: 5621,
    brand: "Sony",
    freeDelivery: true,
  },
  {
    id: 4,
    name: "Nike Air Max 270 React Sneakers (White/Black)",
    slug: "nike-air-max-270",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=500&fit=crop",
    price: 12995,
    originalPrice: 16995,
    rating: 4.4,
    reviewsCount: 1893,
    brand: "Nike",
    freeDelivery: true,
  },
  {
    id: 5,
    name: "Dyson V15 Detect Absolute Cordless Vacuum Cleaner",
    slug: "dyson-v15-detect",
    image: "https://placehold.co/400x500/e8ecf1/8d95a5?text=Dyson",
    price: 52990,
    originalPrice: 62990,
    rating: 4.5,
    reviewsCount: 876,
    brand: "Dyson",
    freeDelivery: false,
  },
  {
    id: 6,
    name: "Canon EOS R6 Mark II Full Frame Mirrorless Camera",
    slug: "canon-eos-r6-mark-ii",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=500&fit=crop",
    price: 249990,
    originalPrice: 279990,
    rating: 4.9,
    reviewsCount: 423,
    brand: "Canon",
    freeDelivery: true,
  },
  {
    id: 7,
    name: "Apple iPad Pro 12.9\" M2 Chip (Space Grey, 256GB WiFi)",
    slug: "ipad-pro-m2",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=500&fit=crop",
    price: 112900,
    originalPrice: 129900,
    rating: 4.8,
    reviewsCount: 1432,
    brand: "Apple",
    freeDelivery: true,
  },
  {
    id: 8,
    name: "Levi's 511 Slim Fit Stretchable Jeans (Dark Indigo)",
    slug: "levis-511-jeans",
    image: "https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=400&h=500&fit=crop",
    price: 3299,
    originalPrice: 5499,
    rating: 4.3,
    reviewsCount: 7854,
    brand: "Levi's",
    freeDelivery: true,
  },
  {
    id: 9,
    name: "JBL Flip 6 Portable Bluetooth Speaker (Teal)",
    slug: "jbl-flip-6",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=500&fit=crop",
    price: 9999,
    originalPrice: 12999,
    rating: 4.5,
    reviewsCount: 3210,
    brand: "JBL",
    freeDelivery: false,
  },
  {
    id: 10,
    name: "Samsung 55\" Crystal OLED 4K Smart TV (2025 Model)",
    slug: "samsung-55-oled-tv",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=500&fit=crop",
    price: 89990,
    originalPrice: 109990,
    rating: 4.6,
    reviewsCount: 1567,
    brand: "Samsung",
    freeDelivery: true,
  },
  {
    id: 11,
    name: "Adidas Ultraboost Light Running Shoes (Core Black)",
    slug: "adidas-ultraboost-light",
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400&h=500&fit=crop",
    price: 14999,
    originalPrice: 19999,
    rating: 4.6,
    reviewsCount: 2345,
    brand: "Adidas",
    freeDelivery: true,
  },
  {
    id: 12,
    name: "Ray-Ban Aviator Classic Sunglasses (Gold/Green)",
    slug: "rayban-aviator-classic",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=500&fit=crop",
    price: 8490,
    originalPrice: 11490,
    rating: 4.7,
    reviewsCount: 4102,
    brand: "Ray-Ban",
    freeDelivery: true,
  },
];
